[Platforms]
# swy: this disables the HiDPI support in Qt6, menus will appear blurry in "Retina"-style/4K screens
# WindowsArguments = dpiawareness=0

# swy: set darkmode to 0 to forcefully disable dark mode, otherwise it should match your OS/global settings
# https://doc.qt.io/qt-6/qguiapplication.html#platform-specific-arguments
# WindowsArguments = darkmode=0

[Paths]
Translations = translations