name: Buildbot
on:
  push:
    branches: [ "redux" ]

jobs:
  build-win:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install the MSVC build tools and Qt
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        # swy: install chocolatey, to make it easy to install other software unattended
        #      then download precompiled versions of qtbase, qttools (for windeployqt) and jom (for a more parallel nmake)
        #      then extract the downloaded qt binaries
        #      turn the qt install from enterprise to foss; remove the licensing checks
        . .\_bring_up_set_up_and_download_qt.ps1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        # swy: configure the msvc environment variables
        #      then configure the Qt environment variables
        #      then run qmake and generate the msvc nmake makefile
        #      finally start the actual build with jom instead of nmake; for speed
        . .\_build.ps1

        # swy: try to add Windows 7 and 8.1 support
        Push-Location _qt_download

        curl.exe -LJ --no-clobber -o qt-unofficial-win7.7z  https://github.com/crystalidea/qt6windows7/releases/download/v6.8.3/qt6_x64_to_run_on_windows7.7z

        7z x qt-unofficial-win7.7z -oqt-unofficial-win7 -y
        
        # swy: replace the DLL files with these retro-compatible versions, the rest work fine
        #      should we rebuild these from source to make sure there is nothing iffy going on? probably.
        #      CrystalIDEA seems to be an actual company that ships actual commercial programs, though.

        cp qt-unofficial-win7/Qt6Core.dll               ../_build
        cp qt-unofficial-win7/Qt6Gui.dll                ../_build
        cp qt-unofficial-win7/Qt6OpenGL.dll             ../_build
        cp qt-unofficial-win7/Qt6OpenGLWidgets.dll      ../_build
        cp qt-unofficial-win7/Qt6Widgets.dll            ../_build
        cp qt-unofficial-win7/platforms/qwindows.dll    ../_build/platforms
        
        Pop-Location

    - uses: actions/upload-artifact@v4
      with:
        name: compiled
        path: ./_build
        retention-days: 90

    - name: Pack things up
      id: pack
      shell: bash
      run: |
        cur_date_ver_tiny="$(date +%Y.%m.%d -u)"
        cur_date_ver_long="$(date +%Y.%m.%d-%H.%M -u)"
        
        cd ./_build
        7z -mm=Deflate -mfb=258 -mpass=15 a "../openbrf-redux-${cur_date_ver_long}.zip" *
        # swy: so that people can validate that the downloaded files were generated by GitHub Actions and not me. Idea from @pbatard, the Rufus author :)
        sha1sum ../*.zip && sha256sum ../*.zip

    - name: Upload Release Asset
      id: upload-release-asset
      shell: bash
      run: |
        # swy: find the release ID just by going here: https://api.github.com/repos/Swyter/openbrf-redux/releases
        owner="swyter"; repo="openbrf-redux"; release_id="147972245"
        
        FILENAME="$(basename "$(find . -name '*openbrf-redux-*.zip' | sort -r -u | head -n 1)")"
        GH_ASSET="https://uploads.github.com/repos/$owner/$repo/releases/$release_id/assets?name=$FILENAME"
        echo "$GH_ASSET"; echo "$FILENAME"
        
        if [[ -f "$FILENAME" ]]; then
          curl --fail --location --data-binary @"$FILENAME" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H "Content-Type: application/octet-stream" "$GH_ASSET"
        else
          echo "[no changes in the folder this time around; skipped]"
        fi